# Generated by Django 3.1 on 2022-04-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
