# Generated by Django 3.1 on 2022-04-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_postimage'),
        ('main', '0002_auto_20220419_1111'),
    ]

    operations = [
    ]
